SELECT ENAME,JOB
FROM EMP
WHERE JOB != 'MANAGER';


SELECT worker.ENAME +'before their'+manager.ENAME
FROM EMP worker,EMP manager
WHERE worker.HIREDATE< manager.HIREDATE;

SELECT COUNT( 'MANAGER') "Number of Managers"
FROM EMP;

SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30,40); 

SELECT ENAME 
FROM EMP
WHERE ENAME LIKE 'T%R';

SELECT ENAME,HIREDATE
FROM EMP
WHERE DEPTNO=30;


SELECT HIREDATE
FROM EMP
WHERE HIREDATE LIKE '%12%';